<a href="https://colab.research.google.com/github/ACrush14/007-IntroducaoAlgebraMatricial/blob/main/C%C3%B3pia_de_1_Introdu%C3%A7%C3%A3o_%C3%A0_Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://www.unifor.br/o/unifor-theme/images/unifor-logo-horizontal.svg' width="250px">

# Álgebra Matricial

Prof. Túlio Ribeiro<br>
Laboratório de Ciência de Dados e Inteligência Artificial (LCDIA)<br>
Universidade de Fortaleza

# Introdução a Matrizes com NumPy
Este notebook apresenta os principais tipos de matrizes, operações básicas e conceitos relacionados como transposta e simetria.


# 1. Conceitos Básicos

## Escalares

In [ ]:
1

1

In [ ]:
# Soma
1 + 2

3

## Vetores

In [ ]:
import numpy as np

u = np.array([1, 1])
print(u)

[1 1]


In [ ]:
v = np.array([1, -1])
print(v)

[ 1 -1]


In [ ]:
# Soma
w = u + v
print(w)

[2 0]


In [ ]:
# Multiplicação por um escalar
w = 3 * v
print(w)

[ 3 -3]


## Matrizes:

In [ ]:
A = np.array([[1, 0, 2],
              [1, 3, 0],
              [2, 1, 2]])
print(A)

[[1 0 2]
 [1 3 0]
 [2 1 2]]


In [ ]:
filtro = A > 50
print("Máscara booleana (A > 50):\n", filtro)

resultado = A[filtro]
print("Elementos maiores que 50:\n", resultado)

In [ ]:
pares = A[A % 2 == 0]
print("Elementos pares:\n", pares)

In [ ]:
print("Segunda linha (índice 1):", A[1])
print("Terceira coluna (índice 2):", A[:, 2])

In [ ]:
submatriz = A[0:2, 1:3]  # linhas 0 e 1, colunas 1 e 2
print("Submatriz 2x2 extraída de A:\n", submatriz)

In [ ]:
A[A < 50] = 0
print("A após zerar valores menores que 50:\n", A)

In [ ]:
B = np.array([[1, 1, 0],
              [0, 1, 0],
              [0, 1, 0]])
print(B)

[[1 1 0]
 [0 1 0]
 [0 1 0]]


In [ ]:
# Adição
C = A + B
print(C)

[[2 1 2]
 [1 4 0]
 [2 2 2]]


In [ ]:
# Multiplicação por um escalar
C = 2 * A
print(C)

[[2 0 4]
 [2 6 0]
 [4 2 4]]


# 2. Tipos de Matrizes

As matrizes podem ser categorizadas de acordo com alguns tipos básicos:

- **Matriz quadrada:** Se possuir o mesmo número de linhas e colunas.

- **Matriz nula:** É uma matriz quadrada ou retangular, onde todas as entradas são nulas.

- **Matriz diagonal:** Se todos os elementos fora da diagonal principal forem nulos.

- **Matriz identidade:** É uma matriz diagonal onde os elementos da diagonal são 1.

- **Matriz escalar:** Se for o produto de um escalar com a matriz identidade.

- **Matriz triangular inferior e superior:** É a uma matriz onde abaixo (ou acima) da diagonal as entradas são todas iguais a zero

-  **Matriz linha e Matriz Coluna:** É a matriz formada por uma linha e n colunas e a matriz formada por n linhas e 1 coluna




**Matriz Quadrada**

In [ ]:
A = np.array([[1, 0, 2],
              [1, 3, 0],
              [2, 1, 2]])

print("Matriz Quadrada:\n", A)
print("Shape:", A.shape)

Matriz Quadrada:
 [[1 0 2]
 [1 3 0]
 [2 1 2]]
Shape: (3, 3)


In [ ]:
print("É quadrada?", A.shape[0] == A.shape[1])

É quadrada? True


In [ ]:
# Matriz Não-quadrada
A = np.array([[1, 0],
              [1, 3],
              [2, 1]])
print("Matriz Não-quadrada:\n", A)
print("Shape:", A.shape)
print("É quadrada?", A.shape[0] == A.shape[1])

Matriz Não-quadrada:
 [[1 0]
 [1 3]
 [2 1]]
Shape: (3, 2)
É quadrada? False


**Matriz Nula**

In [ ]:
Z = np.zeros((3, 3), dtype=int)
print("Matriz Nula:\n", Z)

Matriz Nula:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


**Matriz Diagonal**

In [ ]:
A = np.array([[1, 0, 0, 0],
              [0, 3, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 5]])
print("Matriz Diagonal:\n", A)
print('É diagonal? ' + str(np.allclose(A, np.diag(np.diag(A)))))

Matriz Diagonal:
 [[1 0 0 0]
 [0 3 0 0]
 [0 0 0 0]
 [0 0 0 5]]
É diagonal? True


In [ ]:
A = np.zeros((4, 4), int)

np.fill_diagonal(A, [1, 3, 2, 5])

print("Matriz Diagonal:\n", A)
print('É diagonal? ' + str(np.allclose(A, np.diag(np.diag(A)))))

Matriz Diagonal:
 [[1 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 5]]
É diagonal? True


In [ ]:
np.diag([1, 3, 2, 5])

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 5]])

**Matriz Identidade**

In [ ]:
I = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print("Matriz Identidade:\n", I)
print('É identidade? ' + str(np.allclose(I, np.eye(A.shape[0]))))

Matriz Identidade:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
É identidade? True


In [ ]:
I = np.identity(10, int)

print("Matriz Identidade:\n", I)
print('É identidade? ' + str(np.allclose(I, np.eye(I.shape[0]))))

Matriz Identidade:
 [[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
É identidade? True


In [ ]:
I = np.eye(4)
print("Matriz Identidade:\n", I)

Matriz Identidade:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Matriz Escalar
A = 3 * I
print(A)

[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]


In [ ]:
# Matriz Escalar
E = 3 * np.eye(3)
print("Matriz Escalar (3 * Identidade):\n", E)

Matriz Escalar (3 * Identidade):
 [[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


**Matriz Triangular Inferior e Superior**

In [ ]:
T_inf = np.tril([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Matriz Triangular Inferior:\n", T_inf)

Matriz Triangular Inferior:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
T_sup = np.triu([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Matriz Triangular Superior:\n", T_sup)

Matriz Triangular Superior:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


**Matriz Linha e Matriz Coluna**

In [ ]:
linha = np.array([
    [1, 2, 3]
])
print("Matriz Linha:\n", linha)
print("Shape:", linha.shape)

Matriz Linha:
 [[1 2 3]]
Shape: (1, 3)


In [ ]:
coluna = np.array([
    [1],
    [2],
    [3]
])
print("Matriz Coluna:\n", coluna)
print("Shape:", coluna.shape)


Matriz Coluna:
 [[1]
 [2]
 [3]]
Shape: (3, 1)


# 3. Operações com Matrizes

**Operações Básicas:**
Adição e Multiplicação por escalar

**Produto Matricial:**
Operação entre duas matrizes que resulta em uma terceira matriz.

**Adição de Matrizes**

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A + B:\n", A + B)


A + B:
 [[ 6  8]
 [10 12]]


In [ ]:
# Erro em adição de dimensões diferentes
try:
    A = np.ones((2, 3))
    B = np.ones((3, 2))
    A + B
except ValueError as e:
    print("Erro esperado ao somar matrizes incompatíveis:", e)


Erro esperado ao somar matrizes incompatíveis: operands could not be broadcast together with shapes (2,3) (3,2) 


**Multiplicação por escalar**

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])
print("3 * A:\n", 3 * A)


3 * A:
 [[ 3  6]
 [ 9 12]]


**Produto Matricial**

In [ ]:
A = np.array([
    [1, 2, 5],
    [3, 4, 0]
])

B = np.array([
    [5, 6],
    [7, 8],
    [1, 99]
])

In [ ]:
C = A @ B
D = B @ A

print('Matriz C')
print(C)
print('\nshape:', C.shape)

print('\nMatriz D')
print(D)
print('\nshape:', D.shape)

Matriz C
[[ 24 517]
 [ 43  50]]

shape: (2, 2)

Matriz D
[[ 23  34  25]
 [ 31  46  35]
 [298 398   5]]

shape: (3, 3)


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A * B (element-wise):\n", A * B)
print("A @ B (produto matricial):\n", A @ B)

A * B (element-wise):
 [[ 5 12]
 [21 32]]
A @ B (produto matricial):
 [[19 22]
 [43 50]]


In [ ]:
A.dot(B)

array([[19, 22],
       [43, 50]])

# 4. Propriedades das Operações

**Distributiva: A @ (B + C) = A @ B + A @ C**

In [ ]:
A = np.array([
    [1, 2, 0]
])

B = np.array([
    [1, 0],
    [0, 1],
    [1, 1]
])

C = np.array([
    [2, 1],
    [1, 0],
    [0, 1]
])

esq = A @ (B + C)
dir = (A @ B) + (A @ C)

print("A @ (B + C):\n", esq)
print("A @ B + A @ C:\n", dir)
print("Distributiva confirmada?", np.allclose(esq, dir))

A @ (B + C):
 [[5 3]]
A @ B + A @ C:
 [[5 3]]
Distributiva confirmada? True


**Associativa: (A @ B) @ C = A @ (B @ C)**

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

C = np.array([
    [1, 1],
    [0, 1]
])

print("Associativa confirmada?", np.allclose((A @ B) @ C, A @ (B @ C)))

Associativa confirmada? True


**Multiplicação por Identidade**

In [ ]:
A = np.array([
    [2, 3],
    [4, 5]
])

I = np.eye(A.shape[0])

print("A @ I:\n", A @ I)
print("A @ I == A ?", np.allclose(A @ I, A))


A @ I:
 [[2. 3.]
 [4. 5.]]
A @ I == A ? True


# 6. Matriz Transposta e Matriz Simétrica


**Transposta:** Matriz $A^T$ onde as linhas correspondem às colunas de $A$.


Podemos ainda classificar as matrizes como:

**Matriz simétrica:** Quando $A = A^T$.

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matriz A:\n", A)
print("Transposta de A:\n", A.T)

Matriz A:
 [[1 2 3]
 [4 5 6]]
Transposta de A:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
S = np.array([
    [1, 4, 5],
    [4, 2, 6],
    [5, 6, 3]
])

print("Matriz Simétrica:\n", S)
print("Transposta de S:\n", S.T)
print("É simétrica?", np.allclose(S, S.T))

Matriz Simétrica:
 [[1 4 5]
 [4 2 6]
 [5 6 3]]
Transposta de S:
 [[1 4 5]
 [4 2 6]
 [5 6 3]]
É simétrica? True


In [ ]:
(S == S.T).all()

np.True_

# 7. Recursos e Operações do NumPy


In [ ]:
# Criação e propriedades básicas de arrays

A = np.array([1, 2, 3, 4, 5, 6])

print("Array A:", A)
print("Dimensões (ndim):", A.ndim)
print("Shape:", A.shape)
print("Tamanho total (size):", A.size)
print("Tipo de dados (dtype):", A.dtype)
print("Bytes por elemento:", A.itemsize)

Array A: [1 2 3 4 5 6]
Dimensões (ndim): 1
Shape: (6,)
Tamanho total (size): 6
Tipo de dados (dtype): int64
Bytes por elemento: 8


In [ ]:
# Matriz com tipo específico

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.float64)

print("Matriz B:\n", B)
print("Dimensões:", B.ndim)
print("Shape:", B.shape)

Matriz B:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dimensões: 2
Shape: (2, 3)


In [ ]:
# Criação de matrizes especiais

A = np.zeros((3, 2), dtype=np.int64)  # Matriz de zeros
print("Matriz de zeros:\n", A)

B = np.ones((3, 2))  # Matriz de uns
print("Matriz de uns:\n", B)
print("Tipo dos dados de B:", B.dtype)

C = np.full((2, 2), 10)  # Matriz preenchida com 10
print("Matriz cheia com 10:\n", C)

Matriz de zeros:
 [[0 0]
 [0 0]
 [0 0]]
Matriz de uns:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Tipo dos dados de B: float64
Matriz cheia com 10:
 [[10 10]
 [10 10]]


In [ ]:
# Sequências numéricas

D = np.arange(0, 20, 2)  # Sequência com passo 2
print("arange 0–20:\n", D)

E = np.arange(0, 1, 0.1)  # Sequência com passo decimal
print("arange 0–1 com passo 0.1:\n", E)

F = np.linspace(0, 0.9, 10)  # 10 valores entre 0 e 0.9
print("linspace 0–0.9 (10 pontos):\n", F)

arange 0–20:
 [ 0  2  4  6  8 10 12 14 16 18]
arange 0–1 com passo 0.1:
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
linspace 0–0.9 (10 pontos):
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
# Valores aleatórios

G = np.random.rand(3, 2)  # Aleatórios [0,1)
print("Aleatórios uniformes:\n", G)

H = np.random.randint(0, 10, size=(3, 2))  # Inteiros aleatórios
print("Aleatórios inteiros 0–9:\n", H)

Aleatórios uniformes:
 [[0.833331   0.37305892]
 [0.09640119 0.28974862]
 [0.04005777 0.17674886]]
Aleatórios inteiros 0–9:
 [[5 8]
 [7 3]
 [6 1]]


In [ ]:
# Operações elemento a elemento

a = np.array([10, 20, 30, 40])
b = np.arange(4)

print("Vetor a:", a)
print("Vetor b:", b)

c = a - b
print("a - b:", c)

d = b**2
print("b ao quadrado:", d)

e = 10 * np.sin(a)
print("10 * sin(a):", e)

Vetor a: [10 20 30 40]
Vetor b: [0 1 2 3]
a - b: [10 19 28 37]
b ao quadrado: [0 1 4 9]
10 * sin(a): [-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [ ]:
# Comparação e conversão booleana

f = a < 35
print("a < 35:", f)
print("Tipo lógico:", f.dtype)

g = f * 1  # Converte bool para int (True → 1, False → 0)
print("Conversão para inteiro:", g)
print("Tipo de g:", g.dtype)

a < 35: [ True  True  True False]
Tipo lógico: bool
Conversão para inteiro: [1 1 1 0]
Tipo de g: int64


# Tensores

<img src='https://www.researchgate.net/profile/Dmytro-Shulga/publication/332263806/figure/fig3/AS:745257088086019@1554694544935/Tensors-as-generalizations-of-scalars-vectors-and-matrices.png' heigth="250px">


In [ ]:
A = np.array([
    [
        [1, 1, 3],
        [0, 1, 2],
        [1, 0, 1]
    ],
    [
        [1, 4, 1],
        [0, 2, 1],
        [0, 0, 2]
    ],
    [
        [2, 1, 0],
        [1, 1, 0],
        [1, 0, 4]
    ]
])

print("Tensor A:\n", A)
print("Shape do tensor:", A.shape)

Tensor A:
 [[[1 1 3]
  [0 1 2]
  [1 0 1]]

 [[1 4 1]
  [0 2 1]
  [0 0 2]]

 [[2 1 0]
  [1 1 0]
  [1 0 4]]]
Shape do tensor: (3, 3, 3)


# LIVE EVIL: Ordem da Transposição em Produto de Matrizes

A regra do **LIVE EVIL** é um mnemônico para lembrar como funciona a transposição de produtos de matrizes.  
Ela nos diz que:

$$
(L \cdot I \cdot V \cdot E)^T = E^T \cdot V^T \cdot I^T \cdot L^T
$$

Ou seja, ao transpor um produto de matrizes, **invertemos a ordem** e transpomos **cada matriz individualmente**.

Vamos testar isso com um exemplo prático usando NumPy:


In [ ]:
L = np.array([[1, 2],
              [3, 4]])

I = np.array([[0, 1],
              [1, 0]])

V = np.array([[2, 0],
              [0, 2]])

E = np.array([[1, -1],
              [1,  1]])

# Produto direto: LIVE
LIVE = L @ I @ V @ E

# Transposta do produto
LIVE_T = LIVE.T

# Produto dos transpostos na ordem invertida: E^T V^T I^T L^T
rule_T = E.T @ V.T @ I.T @ L.T

# Verificação
print("LIVE^T:\n", LIVE_T)
print("\nE^T V^T I^T L^T:\n", rule_T)

# Verifica se são iguais
print("\nSão iguais?", np.allclose(LIVE_T, rule_T))

LIVE^T:
 [[ 6 14]
 [-2 -2]]

E^T V^T I^T L^T:
 [[ 6 14]
 [-2 -2]]

São iguais? True
